### PR TITLE
402 userprofile shouted tab 2

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
402-userprofile-shouted-tab - text adapted for single or multiple. / css extended.
 
gif

the basis for this PR is the PR: https://github.com/Human-Connection/Human-Connection/pull/672
### Issues
- relates 402

### Todo

- [X] None

### CODE REVIEW

**Comment by ogerly** [comment]
in the field commented ?
1. comments written by a user in contributions to other users?
or
2. comments he has received on his own contributions?
or
3. Both?
@ulfgebhardt @roschaefer

**Comment by Tirokk** [comment]
> It looks good in general, but it is based on old code and not on the recent `origin master`.
> I can see, because the deletion of a comment is not in it. @ogerly

**Comment by Tirokk** [comment]
Accidentally closed …

**Comment by ogerly** [comment]
giphcccy

**Comment by mattwr18** [comment]
you're so quick @Tirokk... I didn't get a chance to have a proper look, but it looks great @ogerly 
Thanks!!!

Also, I really appreciate people starting to upload screenshots/gif so that others can quickly see the changes!!! @roschaefer @ulfgebhardt

**Pull request merged**
