### PR TITLE
fix(frontend): Post page won't crash on anonymous user

### LINKED ISSUE #2985: 🐛 [Bug] Post page crashes when post author is null
## :bug: Bugreport
We're trying to show or not show the comment form depending on `post.author.blocked`. Unfortunately this will produce an error if the `post.author` is null (anonymous user, deleted user)

### Steps to reproduce the behavior
1. Seed your database and then remove the author from the post manually
2. Visit the post page of this post in your browser
3. App crashes while trying to render the template

### Expected behavior
Comment form should be visible.

### PR DESCRIPTION
**Pull request by roschaefer**
## 🍰 Pullrequest
Seems there was a nullpointer issue with `!post.author.blocked`.

### Issues

- fix #2985 

### Todo

- [X] None

### CODE REVIEW

**Comment by roschaefer** [comment]
@mattwr18 now?

**Comment by mattwr18** [comment]
hey @roschaefer, I asked on the issue you opened as well, but it was unclear to me what you wanted to do with this `PR`

**Comment by mattwr18** [comment]
this failed the build with the error we were discussing today
```
 Notification for a mention

    ✓ Mention another user, re-login as this user and see notifications (19363ms)

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```
this was 13 days ago...

**Comment by roschaefer** [comment]
@mattwr18 I would say let's merge this PR. It does not hurt to assume the `post.author` could be null.

**Pull request merged**
