### PR TITLE
[WIP] i18n-RU translations improvements

### PR DESCRIPTION
**Pull request by vbelolapotkov**
## 🍰 Pullrequest
Improvements to russian translations

Note: plurals for Russian locale accept three forms.
https://github.com/dkfbasel/vuex-i18n/blob/master/src/vuex-i18n-plurals.js#L73

### Issues
- None

### Todo
- [] Check other sections

### CODE REVIEW

**Comment by vbelolapotkov** [comment]
@ewanold fyi, I've created one more PR to add improvements for RU locale. It's still in progress, but feel free to check and ask questions if any.

**Comment by vbelolapotkov** [comment]
@roschaefer, thanks for approval and nice gif 😀 I appreciate your trust as well 🙂, however, the PR is still in progress. I'll remove the [WIP] prefix and ask @ewanold for feedback before final review. What do you think?

**Comment by ewanold** [comment]
@roschaefer I will post a 5-minute intro into the Russian alphabet as soon as Russian is available on HC :-)  then everything will be clear... at least you might be surprised how similar those 2 languages can be.

**Comment by roschaefer** [comment]
@vbelolapotkov @ewanold could you merge this when it's ready? It will pull in your changes into lokalise as well and that might save us from doing things twice.

**Comment by vbelolapotkov** [comment]
@roschaefer sure, will do! It should be ready soon. Just several sections left.

**Comment by Mogge** [comment]
See #2305 . I think we can close this PR

**Comment by vbelolapotkov** [comment]
@Mogge could you please tell me why is it closed? I've just finished the updates and wanted to merge them.
@ewanold  could you please take a look at the overall changes?

**Pull request closed without merging**
