### PR TITLE
Thumbnail in the contribution overview change from 2000px to max-height 357.33px

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
Thumbnail in the contribuion overview with change from 2000px to max-height 357.33px
in the article itself you can see the picture in full size

FireShot Capture 177 - Human Connection - Human Connection - localhost

# before it looked like this

FireShot Capture 178 - Human Connection - Human Connection - localhost

### CODE REVIEW

**Comment by mattwr18** [comment]
we made this change to add 2000px after discussing this with myself, @alina-beck, @DennisHack
it could possibly be decreased, but certainly not down to 350px... I guess we need to discuss further

**Comment by ogerly** [comment]
ok

**Comment by Tirokk** [comment]
We have decided to have big pictures in the newsfeed and in the post itself @ogerly .
For me it looks nice and I love it !!!

Very rear people are doing that. So let them their freedom …

**Comment by ogerly** [comment]
close

**Pull request closed without merging**
