### PR TITLE
Add test coverage

### LINKED ISSUE #469: 🚀 Add testing coverage
## :rocket: Feature

We should have an idea of how much of our app is being tested, and enforce some minimum testing coverage

### Is your feature request related to a problem? Please describe.

We are merging in too many components/features with inadequate or no testing

### Describe the prefered solution and alternatives you've considered

Coveralls and Travis CI combo

### PR DESCRIPTION
**Pull request by mattwr18**
## Pullrequest

this pull request enables jest to collect test coverage

### Issues

- fixes #469 

### Todo

- [ ] set up travis to with codecov
- [ ] add the badge to our README
- [ ] write lots more tests

### CODE REVIEW

**Comment by appinteractive** [comment]
@roschaefer seems to be hard to get coverage for integration/e2e tests but have a look at that discussion: https://github.com/cypress-io/cypress/issues/346

**Comment by mattwr18** [comment]
thanks @appinteractive, I was going to research this later, but you've just saved me time!

**Comment by roschaefer** [comment]
@mattwr18 can we merge this?

**Comment by roschaefer** [comment]
K, @mattwr18 and I were hangouting, and this is OK to merge

**Pull request merged**
