### PR TITLE
Checkbox 'no comercial + no political account' add to creat user account

### LINKED ISSUE #2415: 🚀 [Feature] Registration process: CHECKBOX to confirm "I am non commercial"
## :rocket: Feature
When registering, user must confirm that that he has no commercial interests and is not representing a company or another commercial organisation on the network. 

### User Problem
too many commercial posts on accident, because they often don't know that no commercial interest are allowed AT ALL. Moderation has lots of work

image

### Implementation
Implement a check box at the registration form, so the user has to confirm his private mission (single user accounts) 
"I have no commercial interests and I am not representing a company or any other commercial organisation on the network"
additional INFO Button ("ATTENTION: Commercial behavouring accounts and commercial posts will be ereased immediately and without warning.")

DEUTSCH: 
"Ich habe keiner kommerzielle Absichten und ich representiere kein kommerzielles Unternehmen oder Organisation."
Ergänzende Info an der Checkbox: "ACHTUNG: Kommerziell anmutende Profile und Beiträge werden ohne Vorwarnung gelöscht."

### Design & Layout
FEEL FREE

### Validation
It's less work  for the moderation from the beginning.

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
- Checkbox 'no comercial account' add to creat user account
- Checkbox 'no political account' add to creat user account

### Issues
- fixes #2415
 
FireShot Capture 025 - Human Connection - Human Connection - localhost

FireShot Capture 026 - Human Connection - Human Connection - localhost

### CODE REVIEW

**Comment by roschaefer** [comment]
Can't we just update our terms and conditions and ask to agree with that? There are so many check boxes it's bad user experience.

**Comment by alina-beck** [comment]
I agree with @roschaefer... Other idea – something I've seen quite often before and really like: Make a separate page (or popup) to confirm the terms and conditions and, in addition to the full text (which is the one that's legally binding), sum up the most important points in 'simple' language that is short and humanly readable.

As an example:
> 3. Privacy Statement:
Our network is a social knowledge and action network. It is therefore particularly important to us that as much content as possible is publicly accessible. In the course of the development of our network there will be more and more the possibility to decide about the visibility of the personal data. We will inform you about these new features. Otherwise, you should always think about which personal data you disclose about yourself (or others). This applies in particular to the content of posts and comments, as these have a largely public character. Later there will be possibilities to limit the visibility of your profile. Part of the terms of service is our privacy statement, which informs you about the individual data processing operations in our network: https://human-connection.org/datenschutz/#netzwerk bzw. https://human-connection.org/datenschutz/ Our privacy statement is adapted to the legal situation and characteristics of our network and is always valid in the most current version.

Could be put as:
We take data privacy very serious.
You decide what you want to disclose to third parties.
Your posts and comments are publicly visible.

**Comment by mattwr18** [comment]
I guess we didn't get to discussing this in the standup today... I would agree with the statements :point_up: 
4 check boxes felt like a lot, 5 is getting a little comical...
I guess this discussion should have happened at the planning level before @ogerly put in the work, but here we are...

**Comment by alina-beck** [comment]
Here are two examples for the solution I proposed above @datenbrei:
https://web.500px.com/terms
https://tldrlegal.com/license/instagram-terms-of-use

**Pull request merged**
