### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by appinteractive**
This pull request was initiated by Lokalise (user Mogge) at 2019-11-20 13:03:46

### CODE REVIEW

**Comment by Mogge** [comment]
I changed the configuration to get rid of the `translation` keys from Json (structured) to Json.
grafik

**Comment by Mogge** [comment]
I think this will also close PR #2215

**Comment by ewanold** [comment]
@Mogge  
> I think this will also close PR #2215

I am not sure what is about to close, but i18n-ru takes one or maybe two more days. Vasily is almost done.

**Comment by Mogge** [comment]
@ewanold thanks for the feedback. We push all the languages from lokalise to github about once a week to keep the translations up do date. Do you think we should not use the Russian translation at it is now for any reason? I think it does not matter if only a few translations are missing.

**Comment by Mogge** [comment]
What is happening in this cypress check that is failing?

**Pull request closed without merging**
