### PR TITLE
[WIP] 🍰 Update follower count on follow/unfollow

### LINKED ISSUE #293: Follower count in floating window above user links does not increase
**Describe the bug**
The followers count does not increase. See screenshots …

**To Reproduce**
- If you are in a post of somebody else …
- You hover over the link of the author …
- A floating window appears with the counts of the followers and the counts of his or her posts etc. …
- You are a non follower and click on *following* …

**Expected behavior**
- The followers count does increase.

**Screenshots**
bildschirmfoto 2019-03-06 um 15 14 06
bildschirmfoto 2019-03-06 um 15 14 16

**Desktop (please complete the following information):**
 - macOS FireFox

**Additional context**
Related to old issue #213 .

### PR DESCRIPTION
**Pull request by vbelolapotkov**
## 🍰 Pullrequest
A quick fix to update followedByCount of a followed/unfollowed user in pop up.

### Issues
- fixes #293 

### Todo
- [ ] Update schema and mutation

### CODE REVIEW

**Comment by vbelolapotkov** [comment]
IMO follow/unfollow mutation need to be updated to return more than just boolean result, but followed node as well.
Currently, on a user page, the user query is triggered every time when follow/unfollow is clicked. This can be avoided as well if follow/unfollow mutation can return followed user.

**Comment by Tirokk** [comment]
Hey @vbelolapotkov ,

I had a short overlook and functionally check. 😎🚀
Wonderful quick solution. 🤗

And, because you have the unchecked todo and didn't requested a review, I added the WIP in front of the PR title.

**Comment by Tirokk** [comment]
If you think @vbelolapotkov this is ready for a review then remove the [WIP] (work in progress). 🤗

**Comment by vbelolapotkov** [comment]
@Tirokk as a quick fix it's ready for review but it leads to weird counter transitions on a user page. 
I have suggested a solution above and I'd like to get your feedback on it as it will take time to implement. 
Probably the best solution is to review and merge quick fix, then create a new ticket for further improvement.

**Comment by roschaefer** [comment]
Thank you @vbelolapotkov you rock :guitar: :metal:

**Comment by vbelolapotkov** [comment]
@roschaefer, thanks! Anyways, I'd like to update the resolvers as part of new issue. I'll create one tmw.

**Pull request merged**
