### PR TITLE
fix(webapp): Remove websockets to deploy security hot fix

### LINKED ISSUE #3082: 💥 [DevOps] Remove wsEndpoint to unblock deployment
## :fire: DevOps ticket

At the moment, we have an issue with deploying websockets due to ability to configure websockets_uri for different production environments. See https://github.com/Human-Connection/Human-Connection/issues/3064 and https://github.com/nuxt/nuxt.js/issues/5100

This is blocking our deployment of other features/bug fixes, but most importantly a security related bug fix. If we remove the `wsEndpoint`, it will not try to connect to websockets and we can work on a solution.
### Motive

see :point_up_2: 
### Related issues

see :point_up_2: 
### Implementation

comment out the line in `apollo-config.js`
### Validation

when it's deployed and does not try to connect to websockets, it should be considered successful.

### PR DESCRIPTION
**Pull request by mattwr18**
## 🍰 Pullrequest

Did not 
### Issues

- fixes #3082

### CODE REVIEW

**Comment by mattwr18** [comment]
no, we don't
do you think that is acceptable for a week, or so?

**Comment by mattwr18** [comment]
it might not be difficult actually @Tirokk

**Comment by roschaefer** [comment]
@mattwr18 yes, shall we merge?

**Comment by mattwr18** [comment]
It's failing the build... I added back the poll notifications and it was throwing a `Subscription.notificationAdded returned undefined` error

**Comment by mattwr18** [comment]
Closing since @roschaefer fixed our next build/runtime env variables!!!

**Pull request closed without merging**
