### PR TITLE
Refactor follow unit tests

### PR DESCRIPTION
**Pull request by aonomike**
## 🍰 Pullrequest

Refactor tests to use `apollo-server-testing`
### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by vbelolapotkov** [comment]
Hey @aonomike and reviewers.
FYI, similar changes are in #1596

**Comment by mattwr18** [comment]
yes @vbelolapotkov, we saw that! @aonomike started working to refactor all the backend tests that do not use `apollo-server-testing` at the end of last week, but just pushed up his code yesterday.
He coincidentally started working on the `follow.spec.js`,so there is some duplication of work there, but I think it's ok as his `PR` is to be a larger refactor of the backend tests and yours is to be a sorting out of the `follow/unfollow` work flow.

Maybe you two could even pair?

**Comment by aonomike** [comment]
Hi @vbelolapotkov thanks for reaching out, I think we can continue with your PR on this one, I have seen it. Maybe we can pair ? I will just close this one...

**Comment by vbelolapotkov** [comment]
@aonomike yes sure we can pair! Would you like to have a pair programming session? 
In other case feel free to push on top of `1583-follow-mutation`

**Comment by aonomike** [comment]
@vbelolapotkov sorry I did not see this in time, I contacted you  on discord, not sure if you saw as there has been lots of messages running, and yes I would love a pair programming session!!! I have created a new PR to refactor moderator specs, https://github.com/Human-Connection/Human-Connection/pull/1620

**Pull request closed without merging**
