### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by Lulalaby**
Ignore .github folder on pull.
This directory does not need to get copied.

### CODE REVIEW

**Comment by roschaefer** [comment]
Are you sure? :thinking: I thought we want to keep the issue templates in there. Maybe edit them later

**Comment by roschaefer** [comment]
I think they should be copied locally. E.g. for editing.

Am I missing sth. important?

**Comment by roschaefer** [comment]
aaand they're gone

**Comment by mimicc83** [comment]
uhh yea editing would be helpful at some point ♐️ 
@Lulalaby maybe it should get back into repo? Does it hurt anyone? :)

**Comment by appinteractive** [comment]
It can be edited inside GitHub. My Bad feeling in the stomach is just that it could just disappear 😬

**Comment by Lulalaby** [comment]
It won't if you don't override it ^^
I don't think that anyone would create locally the same file and pushed it to override.
But if you bad feeling is too strong, let's undo this

**Comment by roschaefer** [comment]
let's stay with it for the moment. It can still be edited on Github.

**Comment by appinteractive** [comment]
Let’s keep it like it is for the moment.

**Pull request merged**
