### PR TITLE
convert email to lowercase before submitting

### LINKED ISSUE #2057: 🐛 [Bug] Password-Reset/Registration Dialogue is Case-Sensitive
## :bug: Bugreport
When users want to reset their passwords or want to register and they use emails with uppcercase in it, these can not be found and you get an email which says:  _You requested a password reset but unfortunately we couldn't find an account associated with your e-mail address. Did you maybe use another one when you signed up?_

wrong-email

### Steps to reproduce the behavior
1. Open reset Password dialogue
2. Type in your emial with upper case letters

Screenshot - 2019-10-29T171429 064

Screenshot - 2019-10-29T171929 698

### Expected behavior
The given email for reset should be converted to lowercase

### Version & Environment
any

### PR DESCRIPTION
**Pull request by StephenHogsten**
Convert user inputted email to lowercase when requesting a password reset

### Issues
- fixes #2057

### CODE REVIEW

**Comment by StephenHogsten** [comment]
Just saw the last comment in the issue.  I will take a look at the backend

**Comment by roschaefer** [comment]
@StephenHogsten apparently @Kachulio1 is already working on the backend. Look here:
https://github.com/Human-Connection/Human-Connection/pull/2100

It would be great if you two could join forces :slightly_smiling_face: if you need help to write some tests for the password reset, feel free to ask me for a pair-programming!

**Comment by roschaefer** [comment]
@StephenHogsten and @Kachulio1 I'm going to incorporate your both commits into a dedicated branch and create a PR from that, OK? I'll also add tests.

**Comment by roschaefer** [comment]
@StephenHogsten I'll close this in favour of https://github.com/Human-Connection/Human-Connection/pull/2118 your commit is still there and you'll join the repository's conributors list when it's merged.

**Comment by StephenHogsten** [comment]
@roschaefer just going back through all the comments.  Do you want me to work on anything on the new PR?  Or are other people already taking care of everything?

**Pull request closed without merging**
