### PR TITLE
🍰 2019/kw25/split_graphql_schema

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

split graphql schema

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
I was undecided about this aswell - I decided to split it as much as possible - it is still reversable ;-)

**Comment by appinteractive** [comment]
My approach was to split it by model/topic not by crud. So in theory there should be less files. It’s a more modular approach. I think.

**Comment by ulfgebhardt** [comment]
image
thats my View on this ;-)

**Comment by ulfgebhardt** [comment]
feel free to use this PR to refactor as needed

**Comment by roschaefer** [comment]
Can we close this? I also prefer the CRUDs in one file.

I think I'm gonna close this. If we really need this, we can still re-open.

**Pull request closed without merging**
