### PR TITLE
[WIP] Frontend implementation for notifications

### PR DESCRIPTION
**Pull request by roschaefer**
### Issues
- [X] fixes: #347
- [X] fixes: #348 

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [x] Shall we re-use `PostCard.vue` in `Notification.vue`?
- [x] Write a cucumber test to mark a notification as read

### CODE REVIEW

**Comment by mattwr18** [comment]
on the root path `/`
Screenshot at 2019-04-09 21:25:16
on a post `/post/<id>/<slug>`
Screenshot at 2019-04-09 21:27:58
on a user's profile, it looks the same as on the root path

**Comment by roschaefer** [comment]
@mattwr18 I saw that already. I believe this is a bug on the `PostCard.vue`. Apparently its CSS depends on where you render the component, which is bad.

@mattwr18 question is: Do we actually want to re-use `PostCard.vue` here?

**Comment by mattwr18** [comment]
> @mattwr18 I saw that already. I believe this is a bug on the `PostCard.vue`. Apparently its CSS depends on where you render the component, which is bad.
> 
> @mattwr18 question is: Do we actually want to re-use `PostCard.vue` here?

I didn't upload the photos cause I thought you might not have seen, it was more to help other people understand the issue that we ran into. 
Maybe not? If it is making it tricky to style it, maybe it would be easier to create our own component?

**Comment by mattwr18** [comment]
Currently, we are now getting this failure on the build
```
Opening Cypress...
You've exceeded the limit of private test recordings under your free plan this month. The limit is 500 private test recordings.
To continue recording tests this month you must upgrade your account. Please visit your billing to upgrade to another billing plan.
https://on.cypress.io/dashboard/organizations/ae0b68ee-5e58-4d5b-84aa-11dd163542c4/billing
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run cypress:run --record --key $CYPRESS_TOKEN" exited with 1.
```

**Comment by mattwr18** [comment]
Extracted the `NotificationsPostCard` into its own component to be able to style better
Screenshot at 2019-04-15 19:27:05

It also seemed quite wide to me, so I added a `max-width`, which looks better on mobile in my opinion.. here are some screen shots, what do you all think?
without max-width:
Screenshot at 2019-04-15 19:27:25
with:
Screenshot at 2019-04-15 19:25:32
with max-width wide screen:
Screenshot at 2019-04-15 19:25:53

**Pull request merged**
