### PR TITLE
feat: swap user name<=>handle for discriminability

### LINKED ISSUE #2384: 🚀 [Feature] Swap user unique slug and name
## :rocket: Feature

How about giving the unique user name (aka handle, aka slug) a more noticeable appearance? We could do that by putting the handle on the first line above the user name.

### User Problem

We had a couple of posts where people went crazy because of "hijacked" profiles. Those hijacked profiles was really just a profile with the same data as some other profile, including avatar and name.

### Design & Layout

Screenshot - 2019-11-30T110933 044

### Validation

Well, it's hard to really fix this problem. But maybe it's a step towards the solution.

### Additional context

The posts in our network for reference: 
https://human-connection.social/post/9cd34c9a-034f-4766-892c-3243ba76dc2f/wer-bist-du-1#commentId-ae95880d-84ac-47e3-bf1e-7ca2741d99c3
https://human-connection.social/post/e08c267b-1f02-4e8a-a78f-939d8f9843e3/mein-profil-gehort-mir#commentId-4f80126b-2418-4bc3-b6dd-2ea909e0ac9f

### PR DESCRIPTION
**Pull request by roschaefer**
## 🍰 Pullrequest
Before:
Screenshot - 2019-11-30T110501 902

After:
Screenshot - 2019-11-30T110439 931

### Issues

- fix #2384

### CODE REVIEW

**Comment by alina-beck** [comment]
Not exactly part of the issue but I would love it if we could put the `name` next to the `slug` and the `date` below the two! Think we could do that in this PR?

**Comment by roschaefer** [comment]
@alina-beck 

Screenshot - 2019-12-03T005444 807

?

**Comment by mattwr18** [comment]
great @alina-beck , @roschaefer I was gonna ask for the same thing! 
I think the clock is a little too high for my liking, but certainly this is an improvement... I'll have a better look at the code as soon as I have time

**Comment by roschaefer** [comment]
Well then, two approvals, merge I would say?

**Comment by alina-beck** [comment]
I'll fix the icon position globally – I've seen something similar in other places before. Great work @roschaefer! 😁

**Pull request merged**
