### PR TITLE
Docs 354 kubernetes cron job for backups

### LINKED ISSUE #354: Kubernetes Cronjob to backup Neo4J
We should depend on community edition because we cannot expect sb. who wants to host Human Connection to pay for Neo4J enterprise edition. The community edition has only offline backups available. We need to find a way to download a Neo4J dump regularly in order to avoid data loss.

### PR DESCRIPTION
**Pull request by roschaefer**
## Pullrequest
Dear reviewer, the documentation and the tool velero work as expected on Digital Ocean's kubernetes clusters. However, sometimes I see strange errors like:

```
pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```
or
```
Volume is already exclusively attached to one node and can't be attached to another
```

When I delete/re-apply the deployments with:

```
$ kubectl delete -f deployment/human-connection/deployment-neo4j.yaml -f deployment/human-connection/deployment-backend.yaml
# wait until all objects are torn down
$ kubectl apply -f deployment/human-connection/deployment-neo4j.yaml -f deployment/human-connection/deployment-backend.yaml
```
And wait for a loooooong time ... (~15min)

The cluster is back again. I find it strange but I think this fulfills the requirements for issue #354.
### Issues
- fixes #354

### Checklist

- [X] None

### How2Test

- [ ] Follow the documentation: https://docs.human-connection.org/human-connection/v/docs-354-kubernetes_cron_job_for_backups/deployment/disaster-recovery/velero

### Todo

- [X] None

### CODE REVIEW

**Comment by roschaefer** [comment]
I tried the documented procedure on staging and the cluster fails randomly. I don't know if I will be able to debug the `staging` cluster today, this is what `kubectl get pods --all-namespaces` gives me on my machine:

```
NAMESPACE          NAME                                                            READY   STATUS             RESTARTS   AGE
cert-manager       cert-manager-67884fcbfc-cgbdt                                   1/1     Running            0          50d
cert-manager       cert-manager-webhook-67cfb86d56-dldc5                           1/1     Running            0          50d
cert-manager       cert-manager-webhook-ca-sync-1555804800-nw8rz                   0/1     Completed          0          17d
cert-manager       cert-manager-webhook-ca-sync-1556409600-t9h9m                   0/1     Completed          0          10d
cert-manager       cert-manager-webhook-ca-sync-1557014400-t5zhw                   0/1     Completed          0          3d16h
default            truculent-goat-nginx-ingress-controller-68b469c4b6-lbgsv        1/1     Running            2          50d
default            truculent-goat-nginx-ingress-default-backend-65cc77b574-9vzbx   1/1     Running            1          50d
human-connection   nitro-backend-5b6dd96d6b-8lkrm                                  1/1     Running            0          12m
human-connection   nitro-neo4j-686d768598-5ttl6                                    1/1     Running            0          12m
human-connection   nitro-web-7bf7587896-qc2b6                                      1/1     Running            0          46m
human-connection   nitro-web-7bf7587896-qvdkq                                      1/1     Running            0          46m
kube-system        cilium-4hrjc                                                    0/1     Running            23         71d
kube-system        cilium-bn79q                                                    1/1     Running            13         71d
kube-system        cilium-operator-884664456-22dzt                                 1/1     Running            5065       71d
kube-system        cilium-qjb8m                                                    0/1     Running            19         71d
kube-system        coredns-5d668bd598-9t6d8                                        1/1     Running            9          71d
kube-system        coredns-5d668bd598-p8x76                                        1/1     Running            8          71d
kube-system        csi-do-node-5s7qj                                               2/2     Running            0          71d
kube-system        csi-do-node-9p7k4                                               2/2     Running            0          71d
kube-system        csi-do-node-n74ql                                               2/2     Running            0          71d
kube-system        do-node-agent-bvsrf                                             1/1     Running            0          7d19h
kube-system        do-node-agent-tndxx                                             1/1     Running            0          7d19h
kube-system        do-node-agent-vg6dc                                             1/1     Running            0          7d19h
kube-system        kube-proxy-quizzical-sinoussi-u6en                              1/1     Running            0          71d
kube-system        kube-proxy-quizzical-sinoussi-u6g9                              1/1     Running            0          71d
kube-system        kube-proxy-quizzical-sinoussi-u6gz                              1/1     Running            0          71d
kube-system        kubernetes-dashboard-57df4db6b-fmhwt                            0/1     CrashLoopBackOff   6          50d
kube-system        tiller-deploy-5b7c66d59c-fgnt2                                  0/1     CrashLoopBackOff   11         50d
velero             minio-d9c56ff5-vwlmj                                            1/1     Running            0          14m
velero             minio-setup-2pbwj                                               0/1     Completed          0          14m
velero             restic-bfs87                                                    1/1     Running            0          14m
velero             restic-lv9s8                                                    1/1     Running            0          14m
velero             restic-rwdmf                                                    1/1     Running            0          14m
velero             velero-6f6f6999b-5hzg9                                          1/1     Running            0          14m
```

When I try to debug the crashed kubernetes dashboard with `kubectl logs -n kube-system  kubernetes-dashboard-57df4db6b-fmhwt` I see this:

```
2019/05/08 16:38:43 Using in-cluster config to connect to apiserver
2019/05/08 16:38:43 Using service account token for csrf signing
2019/05/08 16:38:43 Starting overwatch
2019/05/08 16:38:46 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service account's configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.245.0.1:443/version: dial tcp 10.245.0.1:443: connect: no route to host
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
```
What the heck? @appinteractive can you help?

**Comment by roschaefer** [comment]
Ok, https://nitro-staging.human-connection.org/ is available again, but the kubernetes dashboard is dead. 

What. The. Heck.

Screenshot (90)

**Comment by roschaefer** [comment]
And this is how it looks right now... 


Screenshot (91)

**Comment by roschaefer** [comment]
Screenshot (92)


Getting error message when I try to login:
```
Error: GraphQL error: Failed to establish connection in 5000ms
```

It seems, kubernetes on Digital Ocean is also a training of your own patience.

**Comment by mattwr18** [comment]
I am getting the same @roschaefer

**Comment by roschaefer** [comment]
```
robert@e480 ~> kubectl -n human-connection exec -it nitro-neo4j-686d768598-cn929 bash
bash-4.4# cypher-shell
Connected to Neo4j 3.5.0 at bolt://localhost:7687.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
neo4j> match(n) return count(n);
+----------+
| count(n) |
+----------+
| 0        |
+----------+

1 row available after 243 ms, consumed after another 0 ms
neo4j> :exit

Bye!
```

:crying_cat_face:

**Comment by roschaefer** [comment]
Nitro staging: https://nitro-staging.human-connection.org/ is back again, but this time through an offline backup. So backup has failed this time. I'll try to improve the backup strategy tomorrow. Mabye by backing up only persistent volumes (if possible) and not the entire namespace.

**Comment by roschaefer** [comment]
Ok, so today I tried to follow these instructions: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors

The docs specify version `v0.10.0` so I checked out the velero repository at that tag. Check out their documentation here: https://heptio.github.io/velero/v0.10.0/get-started.html

Unfortunately I am not able to create a backup of the two persistent volumes in the namespace `human-connection`. This is what velero gives me:

```sh
$ velero backup --namespace heptio-ark get
NAME          STATUS    CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
hc-backup     New       0001-01-01 00:00:00 +0000 UTC   29d                          app=human-connection
hc-backup-2   New       0001-01-01 00:00:00 +0000 UTC   29d                          app=human-connection
hc-backup-3   New       0001-01-01 00:00:00 +0000 UTC   29d                          app=human-connection
```

```sh
$ velero backup --namespace heptio-ark describe hc-backup-3 --details
Name:         hc-backup-3
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Phase:  New

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=human-connection

Storage Location:

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  0

Started:    <n/a>
Completed:  <n/a>

Expiration:  0001-01-01 00:00:00 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>
```

@appinteractive can we consult digital ocean support on this maybe? I don't think they have up-to-date documentation for backing up persistent volumes in kubernetes.

**Comment by roschaefer** [comment]
I just created a support ticket on Digital Ocean with the following text:

      Dear Digital Ocean Support,

      I setting up Kubernetes for our Application: https://github.com/Human-Connection/Human-Connection

      My goal is to set up some disaster recovery solution. The things we currently
      have to back up are two persistent volumes: One is the volume of a database and
      one volume is an uploads folder with files. If we get those two volumes back
      somehow, I'm happy.

      Problem: I just don't know how?

      Idea 1: Digital Ocean's Web UI has a feature to create a snapshot of a volume.
      You go to https://cloud.digitalocean.com/volumes?i=0f4f57 click on the context
      menu of the volume you want to backup and select "Take a snapshot". While it
      seems to be straight forward to create a backup, I have no idea how to restore
      volumes from the created volume snapshots and re-assign the volumes to a
      kubernetes cluster of my choice and finally create persistent volume claims for
      the already existing volumes.


      Idea 2: Use a kubernetes backup tool like Velero: https://github.com/heptio/velero
      * I tried to follow the docs on version `v0.11.0` with the generic backup
      solutions for persistent volumes called `restic`. While creating the backups
      works, restoring the backup does not work reliably. First, it seems the
      kubernetes cluster is under heavy load and simply crashes sometimes. Second,
      once the pods, deployments and volumes are back, some of the Pods are in a
      "CrashLoop backoff" state and won't recover until I remove the persistent
      volume claims, thus destroying the restored volumes.

      * I tried to follow the Digital Ocean specific backup plugin for velero,
      formerly called `heptio-ark` and this documentation here: https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-a-kubernetes-cluster-on-digitalocean-using-heptio-ark
      The documentation is slightly out-of-date. In order to prevent versioning
      problems, I downgraded velero to the specified version `v0.10.0`. However, when
      I try to create the backup, my persistent volumes are simply not backed up at all.

      See my sequence of frustration in this PR:
      https://github.com/Human-Connection/Human-Connection/pull/573

      Could you please provide some advice on how to backup persistent volumes in a Digital Ocean Kubernetes cluster?

**Comment by mattwr18** [comment]
this is really great @roschaefer... I appreciate you not only documenting the issues you are facing, but also copying and pasting the email you sent to Digital Ocean. I wish I were in a position to help you out more with this. 

The benefit of your approach, the way I see it though, is that in the future someone, maybe even me, will be able to search for and find this and benefit from your documentation of the issue and its solution!! Great work!!

**Comment by roschaefer** [comment]
And Digital Support answered:
> Hi there,
> 
> Thank you for contacting DigitalOcean! To achieve this sort of backup I would look to use kubernetes volumesnapshots:  https://kubernetes.io/docs/concepts/storage/volume-snapshots/
> 
> Luckily our CSI driver fully supports volumesnapshots. You can find examples of volumesnapshot definitions in the documentation above.
> 
> Another option is to use heptio Ark following the guide here:
> 
> https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-a-kubernetes-cluster-on-digitalocean-using-heptio-ark
> 
> Let me know if you have any further questions.
> 
> Regards,
> 
> John Kwiatkoski
> Senior Developer Support Engineer

**Comment by roschaefer** [comment]
@mattwr18 I haven't looked into kubernetes volumesnapshots so that's what I try out next. But the second link that John has sent me :point_up: that's what I already tried with no success.

**Comment by mattwr18** [comment]
great @roschaefer! if you let me know when you are doing it, I will join, if I can

**Comment by roschaefer** [comment]
Well, great, when I run `kubectl apply -f snapshots.yaml` then apparently this creates a volume snapshot on Digital Oceans side.

Visit https://cloud.digitalocean.com/images/snapshots/volumes?i=0f4f57&preserveScrollPosition=true

and see this:

Screenshot (97)


I just don't know how to restore from this Volume Snapshot. The kubernetes docs only mention how to create a volume snapshot, not how to make use of one:
https://kubernetes.io/docs/concepts/storage/volume-snapshots/

Well, I might be mistaken. At least I don't *understand* what I have to do to restore the persistent volume claim.

**Comment by roschaefer** [comment]
My answer to Digital Ocean:
> Hey John,
> 
> thank you for your response!
> 
> I was aware of the second link you mentioned. The docs explain how to use heptio-ark on `v0.10.0` which is quite outdated. The tool is now called `velero`. The problem: I was not able to backup any persistent volumes with that tutorial.
> 
> If you read through the links I've sent you with my support request, you can comprehend what actions I did and what output I expected to see: https://github.com/Human-Connection/Human-Connection/pull/573
> 
> 
> The first link you have sent me is indeed sth. I did not try out already. So here are my findings: https://github.com/Human-Connection/Human-Connection/pull/573#issuecomment-491856682
> 
> My problem now: How can I restore a persistent volume claim from this volume snapshot? Then snapshot showing up on the Digital Ocean Web UI looks very much like what I tried out earlier: I used Digital Ocean Web UI to create a volume snapshot. Apparently the kubernetes volume snapshots behave exactly the same way. I just don't understand how to restore from those volume snapshots. I believe, the kubernetes docs are lacking the explanations here: https://kubernetes.io/docs/concepts/storage/volume-snapshots/
> 
> I also mentioned the volume snapshots by Digital Ocean in my original request and my inability to restore persistent volumes in the cluster from these volume snapshots.
> 
> 
> Cheers,
> 
> Robert

**Comment by roschaefer** [comment]
Here's John's answer (very swift replies :+1: )

> Hi there,
> 
> Thank you for your response. You are correct, that is not abundantly clear how to do this from the kubernetes documentation.
> 
> https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/
> 
> If you scroll down or search for the section: "Provision a new volume from a snapshot with Kubernetes"
> That shows the example definition of a pvc being created from a snapshot.
> 
> For a little overview.:You don't rollback a specific pvc to a volumesnapshot. Instead you create a new pvc using a reference to the volumesnapshosnapshot and then would swap out the pvc so the new deployment begins using the snapshotted data.
> 
> Hope this helps!
> 
> Let me know if you have any further questions.
> 
> Regards,
> 
> John Kwiatkoski
> Senior Developer Support Engineer
>

**Comment by roschaefer** [comment]
We're getting closer. According to "Provision a new volume from a snapshot with Kubernetes" in https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/ I tried to restore a volume snapshot by creating a persistent volume with a `dataSource` attribute pointing to the volume snapshot. Unfortunately, when I bring the deployments back, the database appears to be empty.

Indeed, the persistent volume snapshots show 0 Bytes in file size. Why are they empty?

Screenshot (98)

**Comment by roschaefer** [comment]
Digital Ocean can soon hire us as human testers:
> Hi there,
> 
> Thank you for your patience. The DO CSI driver had a bug in which creating a pvc from a volumesnapshot would not populate the snapshot's data to the new pvc. This bug is fixed in the latest versions of our clusters now.
> 
> If they want or need this functionality, I recommend creating a new cluster at the latest version and migrate over due to this bug. I understand this is a less than optimal solution and I apologise for any inconvenience it causes.
> 
> Let me know if you have any further questions.
> 
> Regards,

**Pull request merged**
