### PR TITLE
845 load more

### PR DESCRIPTION
**Pull request by MoldaB**
### Issues
related #845 
related #253

### CODE REVIEW

**Comment by MoldaB** [comment]
i closed the previous pull request because i was messy there. here is a more elegant solution :)

**Comment by mattwr18** [comment]
hey, this is really great @MoldaB, did you see there are these warnings when running the component tests in `webapp`? `[Vue warn]: Failed to resolve directive: infinite-scroll`
were you able to run the tests locally? get the same output? maybe we can have a pairing session, if you'd like.

**Comment by roschaefer** [comment]
sweet

I like the PR, too! I put in a commit to fix the `console.errors`. From the last build, I believe, the cypress tests are now stalling the build. @mattwr18 let's have a look, if the build server times out again.

**Comment by ogerly** [comment]
i have merge the conflict :)

**Comment by roschaefer** [comment]
@MoldaB thank you for your PR! I investigated why the build server crashes and it seems that the plugin endlessly tries to fetch more posts. This happens especially if there are few results, because infinite scroll will be triggered immediately. Even when `infinite-scroll-immediate-check` is set, it does not stop to call for more posts.

After looking into [vue-infinite-scroll](https://github.com/ElemeFE/vue-infinite-scroll) I was alarmed that the plugin has not seen any commits to the `master` branch [since September 2017](https://github.com/ElemeFE/vue-infinite-scroll/commits/master)! Also it has a long list of confusing, never addressed [issues](https://github.com/ElemeFE/vue-infinite-scroll/issues). It seemed I failed in checking the basics before suggesting you this plugin. Sorry for guiding you in the wrong direction!

So I tried to find a better maintained alternative and found [vue-infinite-loading](https://github.com/PeachScript/vue-infinite-loading). It is quite heavy and also comes with frontend code that we implement ourselves (e.g. spinner icons), but the main argument against it is the problematic API: It has a callback `infiniteHandler` which has a `state` argument and we're supposed to call `state.completed()` once we know there are no more posts. This is not quite what we need: We need to pass a property to the infinite loading component to tell it we're done. So I would not suggest to use it.

Maybe, if we're lucky, we could try to find a better maintained fork of `vue-infinite-scroll`, there are [338](https://github.com/ElemeFE/vue-infinite-scroll/network/members) of them at the moment!

Otherwise I would probably suggest to implement the infinite scroll manually. [It can't be *that* hard](https://www.google.com/search?q=vue+infinite+scrolling+tutorial&oq=vue+infinite+scrolling+tutorial). Maybe we even fork `vue-infinite-scroll` ourselves or copy+paste the useful parts of it?

**Comment by roschaefer** [comment]
@Tirokk, @alina-beck and myself came to the conclusion: Let's add https://github.com/ElemeFE/vue-infinite-scroll and see if we run into any issues with it. So I'm going to merge this PR and say: Thank you @MoldaB for being awesome!

thank you

**Pull request merged**
