### PR TITLE
fix: corrected the code-of-conduct mail link

### LINKED ISSUE #2931: Code of Conduct email link correction
## 💬 Issue
https://human-connection.social/code-of-conduct
Here you find this part at the end:

"If you are subject to or witness unacceptable behavior, or have any other concerns, please notify a community organizer as soon as possible and link or refer to the corresponding content: moderation@human-connection.org"

the email address is linked with: https://human-connection.social/moderation@human-connection.org

Please change it to: mailto:moderation@human-connection.org

### PR DESCRIPTION
**Pull request by adarsh-av13**
## 🍰 Pullrequest
Updated the email link in the Code of Conduct page to point to the right link.

### Issues
- fixes #2931

### CODE REVIEW

**Comment by Tirokk** [comment]
Hi @adarsh-av13 ,
like I said already on the issue:
We are in a heavily transition on the project and I was on holidays for two weeks.
Right back now. 🤗
In the weeks before my holidays we had to sort out a lot of things here which bind our energy.

I recognised you pushed on our master from your fork.
Unfortunately this causes a Travis build error.
It is necessary to clone and push direct on our master to avoid the error.
Therefore I have invited you to our repository as volunteer via an e-mail invitation you can except.
Hope you are still interested.

I feel sorry that we may have annoyed you and go right on your code and review after you pushed direct. 💫

**Comment by mattwr18** [comment]
When @Tirokk says,

> push direct on our master

I believe he is trying to say, push your feature branch to the parent repo and create a `PR` using `master` as the base branch. We have branch protections to prevent everyone, including administrators from pushing to master.

**Comment by adarsh-av13** [comment]
Hi @Tirokk , sorry. I didn't notice this message until now. I just checked and the invitation link has expired. Could you send it again?

**Comment by Tirokk** [comment]
I invited you again @adarsh-av13 🤗

**Comment by Tirokk** [comment]
Closed this PR in favour of the new one …
#3609

**Pull request closed without merging**
