### PR TITLE
🍰 Animate GIF On  Post Card By Mouseover

### LINKED ISSUE #1880: 🚀 [Feature] GIFs: Stop animation on page load, animate on mouseover
## :rocket: Feature

On the posts feed page: Stop GIF animation onload/on mouseout, animate it on mouseover.

### Additional context

Providing a distraction free reading experience.
Coding solution see https://stackoverflow.com/questions/7473117/animating-a-gif-on-hover

### PR DESCRIPTION
**Pull request by yeltawil**
## 🍰 Pullrequest

Writes a script for gifs on page load to run on mouseover. 

### Issues

fixes #1880

### Todo

- [X] couldn't quite test the code as the tests won't work on my machine

### CODE REVIEW

**Comment by mattwr18** [comment]
where do we stand on this @Human-Connection/hc-dev-team ??

**Comment by Tirokk** [comment]
For me that would be great! 💫🚀 @Human-Connection/hc-dev-team

**Comment by mattwr18** [comment]
but you like the approach @yeltawil took @Tirokk ??

**Comment by alina-beck** [comment]
Didn't test this but just checked the code – I'm pretty sure it's not working in the current state and I'm definitely not a fan of importing packages this way... 😅 

@yeltawil do you want to continue working on this feature? If so, please get in touch with us and we can have a look at alternative solutions together! :rocket:

**Pull request closed without merging**
