### PR TITLE
Cursor fixes

### LINKED ISSUE #1438: 🐛 [Bug] Mouse cursor over Logo seems to be non-clickable
## :bug: Bugreport

If the mouse cursor is over the top left logo it does not change to a "hand". This looks like, as if the logo would not be clickable, but it is.

### Steps to reproduce the behavior
1. Move the mouse over the top left logo

### Expected behavior

As on every other clickable part of the page the logo should also be appear as clickable.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [68.0.1]  
 - Device: [Notebook]  

### Additional context

Minor bug, not important, just not nice.

### LINKED ISSUE #1465: 🐛 [Bug] Wrong cursor on post
## :bug: Bugreport
reported by @ulfgebhardt 

The cursor is set to `pointer` on the whole post although there is no interaction possible.

### Steps to reproduce the behavior
1. Go to a post page `/post/something`
2. Hover over the post

### Expected behavior
Only interactive elements should have a `cursor: pointer`

### PR DESCRIPTION
**Pull request by alina-beck**
## 🍰 Pullrequest
- sets cursor to pointer for header logo
- removes pointer from post

### Issues
- fixes #1438 
- fixes #1465

### CODE REVIEW

**Comment by alina-beck** [comment]
@roschaefer Oh yeah, sorry, I saw this too late! Unfortunately the above command gives me `fatal: invalid reference: 1394-simplify_index_page` – any idea why? I could also just copy the content of the files otherwise...

**Comment by roschaefer** [comment]
@alina-beck yes! That's because you don't have the local branch `1394-simplify_index_page`. You could check out the files from the remote branch `origin/1394-simplify_index_page` though.

**Comment by alina-beck** [comment]
@roschaefer duh. thank you! 😅 how come we don't need the `posts` store anymore, though? is it not being used anywhere else?

**Comment by roschaefer** [comment]
the `posts` store was dead code after #1233

**Pull request merged**
