### PR TITLE
chore: 🍰 [WIP] Deploy Backend And Neo4j Resources Requests And Limits

### LINKED ISSUE #2628: 🐛 [Bug] Backend Exceeds Heap Size Limit and Restarts
## :bug: Bugreport

Before Christmas the backend restarted every 5 minutes.

Matt and I have found that the heap size of the backend by default should be 1.5Gi.

It seems that we have to define:

```yaml
    spec:
      containers:
        resources:
          requests:
            memory: XXX
            cpu: XXX
          limits:
            memory: XXX
            cpu: XXX
```

And that should be done for the Neo4j database as well where only `requests. memory` was already defined.

See:
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits

### Steps to reproduce the behavior

Restarted 24 time since 21.12.2019 …
But does not since 25.12.2019 …

### Expected behavior

Should not restart by error.

### Additional context

Suggestions in VSCode are:

Bildschirmfoto 2019-12-23 um 10 25 52

Bildschirmfoto 2019-12-23 um 10 25 28

May we have to set `requests` and `limits` for web app as well!?

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pullrequest

Hopefully fixes the heap size error of the backend and went into better organisation of Kubernetes resources.

- [ ] May we have to set requests and limits for the webapps as well!?

This all has to be discussed.

### Issues

- fixes #2628

### Todo

- [ ] ? (see above)
- [ ] we have merged a potential fix into master and will deploy to production on 13/01/2020, then we can revisit this, agree on sensible limits, and test them before merging(?)

### CODE REVIEW

**Comment by mattwr18** [comment]
can this be closed? or can you link to the docs you found describing why this is good to set @Tirokk ??

**Comment by mattwr18** [comment]
should we discuss this, close it @Tirokk

**Comment by Tirokk** [comment]
The reason is to discuss is in the related and fixed issue #2629 (was already closed and now reopened).

See:
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits

**Comment by Tirokk** [comment]
This was successful at the end.
So I close this one …

But there is still a problem see #3648 .

**Pull request closed without merging**
