### PR TITLE
[TEST] Save user setting to show embed code

### LINKED ISSUE #1684: 🚀 [Feature] save embeds iframe permanently
## :rocket: Feature
save embeds iframe permanently. 

prerequisite the following PRs are merged

### PR DESCRIPTION
**Pull request by ogerly**
continue here #1852

### CODE REVIEW

**Comment by ogerly** [comment]
zu https://github.com/Human-Connection/Human-Connection/pull/1686/commits/e8f771b59aca0ff25df41f0867ec9b4d443c8473 
https://youtu.be/SFKWenwSAvM

**Comment by alina-beck** [comment]
@ogerly I found the `setNodeMarkup` transformation [in the prosemirror docs](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup) – not sure this is what we need but it sounds like it could help us turn the `Embed` into a `Link` node... maybe? 🙂

**Comment by ogerly** [comment]
nice @mattwr18 thanks !!!!

**Comment by ogerly** [comment]
ok
 
giphy

**Comment by ogerly** [comment]
continue here  https://github.com/Human-Connection/Human-Connection/pull/1852

**Pull request merged**
