### PR TITLE
Added PRIVATE_KEY_PASSPHRASE to needed env vars

### PR DESCRIPTION
**Pull request by Mastercuber**

### CODE REVIEW

**Comment by Mastercuber** [comment]
depend on #243

**Comment by roschaefer** [comment]
@Mastercuber I've merged #243 could you:
1. `git fetch upstream/master`
2. `git rebase upstream/master`
3. `git push upstream needed-env-vars --force`

please?

I would like to clean up commits in this PR.

**Comment by roschaefer** [comment]
@Mastercuber squash please :green_heart:

**Comment by Mastercuber** [comment]
Is done!

**Comment by roschaefer** [comment]
@Mastercuber Oh, I'm sorry. When I said `squash` I forgot to mention that you better also rebase on the latest `origin/master`. Otherwise we have a lot of conflicts, see above.

**Comment by roschaefer** [comment]
@Mastercuber *after* you merged `origin/master` or rebased on `origin/master` you can squash the commits. That should clean up the history a little.

**Pull request merged**
