### PR TITLE
Update to 0.1.2

### PR DESCRIPTION
**Pull request by mattwr18**
Version bump

### CODE REVIEW

**Comment by mattwr18** [comment]
I'm not sure why the `CHANGELOG` is merged... it's how the tool `github_changelog_generator` works, I guess.. I would prefer it the way you suggest as well, makes it much easier to see what was changed when... I'll have a look at the docs and see if there are flags that give us the desired output...

**Comment by roschaefer** [comment]
@mattwr18 
```
rm CHANGELOG.md
git-generate-changelog --some --params --since-tag 0.1.1
```
Maybe?

**Comment by mattwr18** [comment]
I could give it a go @roschaefer

**Comment by mattwr18** [comment]
tried that out, and it gave the same output as before @roschaefer

**Comment by mattwr18** [comment]
ok, I updated the release with the diff... but I guess I need to generate this directly before deploying the latest changes, not the day before cause there were a few `PR`s merged in that happened after this was generated

**Pull request merged**
